# Generated by Django 5.2.15 on 2026-06-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_calc_method_yield_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_weight',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
    ]
